run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
